### ISSUE TITLE
Private Repository Support

### ISSUE THREAD

**Issue by cmccarthy101** [cloudfoundry/go-mod-cnb#3]
Using master of go-mod-cnb

### What version of the buildpack you are using?

master branch

### If you were attempting to accomplish a task, what was it you were attempting to do?

Build source code using the go-mod-cnb buildpack where a module references code from a private git repo.

### What did you expect to happen?

I expected some input or method to provide credentials to the buildpack to build the container image. 

### What was the actual behavior?

We got the following error as when git tried to fetch from a private repo, it wanted to prompt the user for a username and password to access, but couldn't. 
```
[builder] go: finding github.com/cmccarthy101/test10 v0.0.0-20190508160027-f70a194aee79
[builder] go: github.com/cmccarthy101/test10@v0.0.0-20190508160027-f70a194aee79: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /layers/org.cloudfoundry.go-mod/go-mod/pkg/mod/cache/vcs/1c0e1ed356a540e8b5b7244633737b2ebac6042801011dba950572c2525b76c3: exit status 128:
[builder] 	fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

### Can you provide a sample app?

https://github.com/cmccarthy101/test11.git

// @benchapman

**Comment by chhhavi** [comment]
Hi @cmccarthy101,
Thanks for filing this issue. We don't currently support this behavior in the `go-mod-cnb` and don't support this behavior in our `go-buildpack` as well. If you have dependencies in private repositories, an option could be to vendor your packages.

**Comment by sclevine** [comment]
There's some discussion on slack about this:
https://buildpacks.slack.com/archives/C94UJCNV6/p1557344013277100

In general, build-time environment variables can be used to inject credentials (e.g., `--env-file` with `pack`), but in this case, [git can't read creds from environment variables](https://stackoverflow.com/questions/8536732/can-i-hold-git-credentials-in-environment-variables).

I think we have a few options:
- A `pack` feature that lets you inject an SSH key
- A simple v3 buildpack that lets you inject an SSH key
- A simple v3 buildpack that creates a git credential helper from the environment (see the link above)

Regardless, not a feature that the go-mod-cnb should support directly.

**Comment by shanks3012** [comment]
For now, we suggest that you vendor your modules as a workaround while we see abut prioritizing this feature. Let us know if this does is not possible for you. Thanks.

**Comment by tillyt** [comment]
Closing for now as a workaround was given. Definitely reopen if still an issue!

**Comment by prima101112** [comment]
Hi, kaniko are supporting injecting build vars (could be ssh key) that used in dockerfile. we using kaniko for now and try to make build more faster and easy for new service to onboard on our CI CD.

the question is, are pack will be able to do that? if its end up we build our own builder then whats different with creating our dockerfile cc @tillyt
