### ISSUE TITLE
Source code should not be included in run container

### ISSUE THREAD

**Issue by cmccarthy101** [cloudfoundry/go-mod-cnb#4]
### What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of 

running `cf curl /v2/info && cf version`?
`pack cli v0.1.0 (git sha: e1793ab9fc3d172a416183ef3df20daf089eba19)`

### What version of the buildpack you are using?
`v0.2.0`

### If you were attempting to accomplish a task, what was it you were attempting to do?

N/A

### What did you expect to happen?

Source code should not be included in the run container once the Go code has been compiled

### What was the actual behavior?

Source code was included in the run container once the Go code was compiled

### Can you provide a sample app?

Any app will do

/cc @benchapman

**Comment by tylerphelan** [comment]
@cmccarthy101 definitely true! We will prioritize this soon.

**Comment by ndon55555** [comment]
Hi @cmccarthy101, this commit https://github.com/cloudfoundry/go-mod-cnb/commit/7bc499e06448395daa5a0ffc7367dd2cd80611dc should fix this issue and will be included in the next release.
