### ISSUE TITLE
v0.0.15 released but 0.0.9 is in `cflinuxfs3` image

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/go-mod-cnb#5]
```
$ docker run -ti cloudfoundry/cnb:cflinuxfs3 bash -euc "ls /buildpacks/org.cloudfoundry.go-mod/"
0.0.9  latest
```

Sorry for using issues for my own learning.

Why is 0.0.15 the latest version of this buildpack (7 days ago), but https://github.com/cloudfoundry/go-mod-cnb/releases/tag/v0.0.9 from 26 days ago is the version in the builder?

**Comment by sclevine** [comment]
The later releases have moved to buildpack API contract 0.2, and can’t be included in the builder until the next lifecycle release (0.4.0). That release is on track for tomorrow, so we should be able to bump all the CF CNBs in the builder soon.

**Comment by drnic** [comment]
Ok cool. Sorry that I started investigating this stuff again during this transition phase.
