### ISSUE TITLE
CNB lifecycle can't restore cached layer for go-mod

### ISSUE THREAD

**Issue by bstick12** [cloudfoundry/go-mod-cnb#6]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
N/A - Was testing the `go-mod` using kpack

What version of the buildpack you are using?
org.cloudfoundry.go-mod@0.0.17

If you were attempting to accomplish a task, what was it you were attempting to do?
Rebuild an image using kpack where caching was enabled

What did you expect to happen?
The image would be re-built using the cached layers

What was the actual behavior?
The lifecycle of CNB fails at `restore` as the layer tar can be uncompressed

```
Restoring cached layer 'org.cloudfoundry.go-mod:go-mod'
Error: failed to restore: mkdir /layers/org.cloudfoundry.go-mod/go-mod/pkg/mod/github.com/bstick12/goflake@v1.0.0/.circleci: permission denied
```

The previous layer is correctly used from cache

```
Restoring cached layer 'org.cloudfoundry.go-compiler:ac2a6efcc1f5ec8bdc0db0a988bb1d301d64b6d61b7e8d9e42f662fbb75a2b9b'
Restoring cached layer 'org.cloudfoundry.go-compiler:go'
```

The problem lies with the go module package paths. The package directories are not writeable. Apparently this is by design as discussed in https://github.com/golang/go/issues/27161 and https://github.com/golang/go/issues/27455#issuecomment-417997868

```
  File: /layers/org.cloudfoundry.go-mod/go-mod/pkg/mod/github.com/bstick12/goflake@v1.0.0/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 6ch/108d	Inode: 300555      Links: 4
Access: (0500/dr-x------)  Uid: ( 1000/     cnb)   Gid: ( 1000/     cnb)
```

This permission is preserved in the tarball

```
dr-x------ 1000/1000         0 1980-01-01 00:00 /layers/org.cloudfoundry.go-mod/go-mod/pkg/mod/github.com/bstick12/goflake@v1.0.0
d
```

Since without a change to the tar or untaring process for this buildpack the caching process will break. Would be possible to disable caching. 

Can you provide a sample app?

The behaviour should be the same for any go application that use  go modules. 

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @bstick12,

This appears to be an issue with the CNB lifecycle. It should be possible to restore layers regardless of their permissions. The lifecycle should implement the equivalent of `tar --delay-directory-restore -x...`.

Would you mind opening an issue here?
https://github.com/buildpack/lifecycle

**Comment by bstick12** [comment]
Thanks @sclevine. I've opened https://github.com/buildpack/lifecycle/issues/177

**Comment by thitch97** [comment]
@bstick12 Closing this issue in favor of [buildpack/lifecycle#177](https://github.com/buildpack/lifecycle/issues/177).
