### ISSUE TITLE
Add built app-binary to the path on launch

### ISSUE THREAD

**Issue by matthewmcnew** [cloudfoundry/go-mod-cnb#8]
What version of the buildpack you are using?
org.cloudfoundry.go-mod- 0.0.29

What did you expect to happen?
I expected the built binary to be on the pack at launch. 

What was the actual behavior?
The app binary is in /layers/org.cloudfoundry.go-mod/app-binary/build-init instead of /layers/org.cloudfoundry.go-mod/app-binary/bin/build-init

Can you provide a sample app?
http://github.com/pivotal/kpack

**Comment by thitch97** [comment]
Resolved in https://github.com/cloudfoundry/go-mod-cnb/commit/babdd6cbe22533e6b4c9d9e6fd81513b0bd8a14f
